/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorWorkArea;
import Project.Medicine.PrescriptionService;
import Project.Medicine.PrescriiptionnList;
import Project.EcoSystem;
import Project.Venture.Venture;
import Project.MedicalEmployment.DoctorService;
import Project.MedicalEmployment.PatientDetails;
import Project.Medicine.MedicineService;
import Project.Network.NetworkService;
import Project.Organization.DoctorOrganizationService;
import Project.Organization.MedicineOrganizationService;
import Project.Organization.OrganizationService;
/////import Business.OrganizationService.PharmacyOrganization;
import Project.UserAccount.UserAccountService;
import Project.WorkQueue.DoctorWorkRequestService;
import Project.WorkQueue.WorkRequestService;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
/**
 *
 * @author Dell
 */
public class PrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrescriptionJPanel
     */
      private OrganizationService organization;
    private Venture enterprise;

    private UserAccountService userAccount;
    private JPanel userProcessContainer;
    //private PrescriptionService prescription;
    private DoctorWorkRequestService docreq;
    private NetworkService network;
    private EcoSystem system;
    private static Logger log = Logger.getLogger(PrescriptionJPanel.class);
    private static final String CLASS_NAME = PrescriptionJPanel.class.getName();
    private static final String filePath = "./prescription data.txt";
    private PatientDetails patient;
    private DoctorService doctor;
    public PrescriptionJPanel(JPanel userProcessContainer, UserAccountService account, Venture enterprise, 
            OrganizationService organization, 
            EcoSystem system, NetworkService network,PatientDetails patient,DoctorService doctor) {
        initComponents();
         this.doctor = doctor;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        this.system = system;
        this.patient = patient;
        
        //populateWorkRequestTable();
        jDateChooser.setMinSelectableDate(new Date());
        populatefields();
        populateMedicineCmb();
        //populateWorkRequestTable();
    }
    
    public void populatefields()
    {
        jtxtName.setText(patient.getPatName());
        jtxtAge.setText(String.valueOf(patient.getPatAge()));
        jtxtGender.setText(patient.getPatGender());
    }

    public void populateMedicineCmb()
    {
        jcbMedicine.removeAllItems();
        jcbMedicine.addItem("Select");
        for(Venture enter : network.getVentureDirectory().getVentureList())
        {
            for(OrganizationService org : enter.getOrganizationDirectory().getOrganizationList())
            {
                if(org instanceof MedicineOrganizationService)
                {
                    MedicineOrganizationService medOrg = (MedicineOrganizationService) org;
                    for(MedicineService med : medOrg.getMedList())
                    {
                        jcbMedicine.addItem(med.getMedName());
                    }
                    
                }
            }
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkLabel1 = new javax.swing.JLabel();
        jkLabel2 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jkLabel3 = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jkLabel4 = new javax.swing.JLabel();
        jtxtGender = new javax.swing.JTextField();
        jkLabel5 = new javax.swing.JLabel();
        jcbMedicine = new javax.swing.JComboBox<>();
        jkLabel6 = new javax.swing.JLabel();
        jnoofTimesTxt = new javax.swing.JSpinner();
        jkLabel7 = new javax.swing.JLabel();
        jnoofDaysTxt = new javax.swing.JSpinner();
        jkButton1 = new javax.swing.JButton();
        jkLabel8 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriJTable = new javax.swing.JTable();
        jbtnBack = new javax.swing.JButton();
        jkButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jkLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel1.setText("DOCTOR PRESCRIPTION");
        add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 17, 312, 40));

        jkLabel2.setText("Name :");
        add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 90, -1, -1));

        jtxtName.setEditable(false);
        add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 85, 167, -1));

        jkLabel3.setText("Age:");
        add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 146, -1, -1));

        jtxtAge.setEditable(false);
        add(jtxtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 141, 167, -1));

        jkLabel4.setText("Gender:");
        add(jkLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 202, -1, -1));

        jtxtGender.setEditable(false);
        add(jtxtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 197, 167, -1));

        jkLabel5.setText("Medicine:");
        add(jkLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 257, -1, -1));

        jcbMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jcbMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 253, 167, -1));

        jkLabel6.setText("Times a Day:");
        add(jkLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 315, -1, -1));
        add(jnoofTimesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 310, 167, -1));

        jkLabel7.setText("For:");
        add(jkLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 371, -1, -1));
        add(jnoofDaysTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 366, 167, -1));

        jkButton1.setText("Add to Prescription");
        jkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkButton1ActionPerformed(evt);
            }
        });
        add(jkButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 267, -1));

        jkLabel8.setText("Date: ");
        add(jkLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 422, -1, -1));
        add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 422, 167, -1));

        prescriJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Medicine", "No of Times", "Days"
            }
        ));
        jScrollPane1.setViewportView(prescriJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 557, 560, 139));

        jbtnBack.setText("<<Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 190, -1));

        jkButton2.setText("Send Prescription To Customer");
        jkButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkButton2ActionPerformed(evt);
            }
        });
        add(jkButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        log.debug("going back to Doctors work area");
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkButton1ActionPerformed
        // TODO add your handling code here:
         PrescriptionService p = new PrescriptionService();
       // p.setDaignosis(diagnosisComboBox.getSelectedItem().toString());
        p.setMedName(jcbMedicine.getSelectedItem().toString());
        p.setNumberOfTimesInaday((Integer) jnoofTimesTxt.getValue());
        p.setTotallDays((Integer) jnoofDaysTxt.getValue());
        p.setNetworkkName(network.getNetName());
        
        
        
//        String age = ageTxtField.getText();
        boolean flag = true;
        try {
           // Integer.parseInt(age);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age must be integer!");
            flag = false;
            return;
        }

       // if (p.getDaignosis().equals("")) {
           // JOptionPane.showMessageDialog(null, "Please enter the daignosis!");
          //  flag = false;
          //  return;
        //} else 
//        if (nameTxtField.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Please enter the patient name!");
//            flag = false;
//            return;
//
//        }
         if(((Integer) jnoofTimesTxt.getValue())==0|| ((Integer) jnoofDaysTxt.getValue())==0)
                {
                     JOptionPane.showMessageDialog(null, "Please enter the no of days or no times !");
             flag = false;
             return;
                }
         if(jDateChooser.getDate()==null)
         {
             JOptionPane.showMessageDialog(null, "Please select the date !");
             flag = false;
             return;
         }
         System.out.println("cbMedicine.getSelectedIndex() "+  jcbMedicine.getSelectedIndex());
         if(jcbMedicine.getSelectedIndex()<=0)
         {
             JOptionPane.showMessageDialog(null, "Please select the Medication Name !");
             flag = false;
         }
//         if(sexcomboBox.getSelectedIndex()<=0)
//         {
//          JOptionPane.showMessageDialog(null, "Please select the Medication Name !");
//             flag = false;   
//             return;
//         }

        
        if (flag == true) {
            
            
            patient.getPrescriptionList().addPrescriiption(p);

//            PharmacyWorkRequest request = new PharmacyWorkRequest();
//
//            request.setMedicationName(medicationCombobox.getSelectedItem().toString());
//            request.setQuantity(((Integer) noofTimesTxt.getValue()) * ((Integer) noofDaysTxt.getValue()));
//            request.setSender(userAccount);
//            request.setStatus("Sent");
//            System.out.println(request.getMedicationName());
//            JOptionPane.showMessageDialog(null, "PrescriptionService added successfully");
//
//            System.out.println("****" + enterprise.getName());
//            OrganizationService org = null;
//
//                for (Venture enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//                    for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//                        if (organization instanceof PharmacyOrganization) {
//                            org = organization;
//                            System.out.println("****" + org);
//                            log.debug(org);
//                            log.debug("Current Venture\t" +enterprise);
//                               log.debug("Current OrganizationService\t" +org);
//                               log.debug("Current NetworkService\t" +network);
//                            break;
//                        }
//                    }
//                }
//            
//            if (org != null) {
//
//                org.getWorkQueue().getWorkRequestList().add(request);
//                userAccount.getWorkQueue().getWorkRequestList().add(request);
//                log.debug("request sent to Pharmacy");
//            }
            
           

            populateWorkRequestTable();
            saveRecord(p.getNetworkkName(),p.getDaignosiss(),p.getMedName(),p.getNumberOfTimesInaday(),p.getTotallDays());
           // txtName.setText("");
           // ageTxtField.setText("");
             jnoofTimesTxt.setValue(0);
             jnoofDaysTxt.setValue(0);
           //  sexcomboBox.setSelectedIndex(0);
             jcbMedicine.setSelectedIndex(0);
            
        }

        
    }//GEN-LAST:event_jkButton1ActionPerformed

    public void populateWorkRequestTable() {

        DefaultTableModel model = (DefaultTableModel) prescriJTable.getModel();

        model.setRowCount(0);

        for (PrescriptionService prescription : patient.getPrescriptionList().getPrescriiptionList()) {
           
                Object[] row = new Object[5];
                row[0] = prescription.getMedName();
                row[1] = prescription.getNumberOfTimesInaday();
                row[2] = prescription.getTotallDays();         
                model.addRow(row);
        }

    }
    private void jkButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkButton2ActionPerformed
        // TODO add your handling code here:
        
        log.info("Prescritopn Send to Customer");
        String prescrip ="";
        for (PrescriptionService prescription : patient.getPrescriptionList().getPrescriiptionList()) {
           
               
               prescrip += "Medicine Name : "+prescription.getMedName();
               prescrip += ", No of times a Day : " + prescription.getNumberOfTimesInaday();
              prescrip  += ", No of Days" + prescription.getTotallDays();         
            
        }
        
        SendEmail(patient.getEmailAdd(),prescrip);
        
    }//GEN-LAST:event_jkButton2ActionPerformed

    public void saveRecord(String network,String disease,String medicine,int times, int days){
        try {
            FileWriter file = new FileWriter(filePath,true);
            BufferedWriter bw = new BufferedWriter(file);
            PrintWriter pw = new PrintWriter(bw);
            pw.println("Medicine Name - " + medicine+", No of Times "+times + ", No of Days"+days);
            pw.flush();
            pw.close();
            log.debug("saving prescription details to prescription data.txt");
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(PrescriptionJPanel.class.getName()).log(Level.SEVERE, null, ex);
            log.error("prescription data.txt" +ex);
           
        }
        
    }
    
    public void SendEmail(String emailAddress, String Prescription)
    {
        System.out.println("Inside Email ");
         String to = emailAddress;
        String from = "donotreplymedicalemergency@gmail.com";
        String pass = "Password@123";
// Assuming you are sending email from localhost
// String host = "192.168.0.16";

// Get system properties
        Properties properties = System.getProperties();
        String host = "smtp.gmail.com";

        properties.put("mail.smtp.starttls.enable", "true");

        properties.put("mail.smtp.ssl.trust", host);
        properties.put("mail.smtp.user", from);
// properties.put("mail.smtp.password", pass);
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.auth", "true");

// Setup mail server
// properties.setProperty("mail.smtp.host", host);
// properties.put("mail.smtp.starttls.enable", "true");
// Get the default Session object.
        Session session = Session.getDefaultInstance(properties);

        try {
// Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

// Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

// Set To: header field of the header.
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            String htmlText = ("<div style=\"color:red;\">BRIDGEYE</div>");
            message.setContent(htmlText, "text/html");

// Set Subject: header field
            message.setSubject("Patient Registration");
            
            
            String msg = "Doctor Prescription - ";
            msg += Prescription;
                    
// String text= "<table><tr><td>EmpId</td><td>Emp name</td><td>age</td></tr><tr><td>value</td><td>value</td><td>value</td></tr></table>";
            message.setText(msg);
// Send message
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
                JOptionPane.showMessageDialog(null,"Sent message successfully....");
            System.out.println("Sent message successfully....");
        } catch (MessagingException mex) {
            mex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Invalid email id");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JComboBox<String> jcbMedicine;
    private javax.swing.JButton jkButton1;
    private javax.swing.JButton jkButton2;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JLabel jkLabel5;
    private javax.swing.JLabel jkLabel6;
    private javax.swing.JLabel jkLabel7;
    private javax.swing.JLabel jkLabel8;
    private javax.swing.JSpinner jnoofDaysTxt;
    private javax.swing.JSpinner jnoofTimesTxt;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtGender;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTable prescriJTable;
    // End of variables declaration//GEN-END:variables
}
