/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorWorkArea;

import Project.EcoSystem;
import Project.Employee.Employee;
import Project.Venture.Venture;
import Project.MedicalEmployment.DoctorService;
import Project.MedicalEmployment.PatientDetails;
import Project.Network.NetworkService;
//import Business.Mail.Mail;
import Project.Organization.LabOrganizationService;
import Project.Organization.OrganizationService;
import Project.UserAccount.UserAccountService;
import Project.WorkQueue.LabTestWorkRequestService;
import Project.WorkQueue.LabWorkRequestService;
import Project.WorkQueue.WorkRequestService;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
////import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dell
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestLabTestJPanel
     */
    
    private JPanel userProcessContainer;
    private Venture enterprise;
    private UserAccountService userAccount;
    private PatientDetails patient;
    private EcoSystem ecosystem;
    OrganizationService organization;
    DoctorService doctor;
    NetworkService network;
    
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccountService account, Venture enterprise, PatientDetails patient,
            DoctorService doctor, OrganizationService organization,NetworkService network, EcoSystem business) {
        initComponents();
         this.ecosystem = business;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.patient = patient;
        this.doctor = doctor;
        this.organization = organization;
        this.network = network;
        
        populateTable();

        //valueLabel.setText(enterprise.getName());
        jlblDocName.setText(doctor.getDoctorName());
        jlblPatientName.setText( patient.getPatName());
    }
    
     public void populateTable()
    {
        
         DefaultTableModel model = (DefaultTableModel) jtblLabRequest.getModel();
        model.setRowCount(0);
        
         OrganizationService org = null;
       for(Venture enterprise : network.getVentureDirectory().getVentureList())  
       {
            for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof LabOrganizationService) {
                    System.out.println(organization.getTypee());
                    org = organization;
                    break;
                }
            }
       }
        if (org != null) {
            for(WorkRequestService wr : org.getWorkkQueue().getWorkRequestList())
            {
                if(wr instanceof LabWorkRequestService)
                {
                    LabWorkRequestService lwr = (LabWorkRequestService)wr;
                    if(lwr.getPati().equals(patient))
                    {
                        Object[] row = new Object[6];
                        row[0] = lwr.getLabTestReqId();
                        row[1] = lwr.getPati().getPatName();
                        row[2] = lwr.getSpeciType();               
                        row[3] = lwr.getLabTesttName();
                        row[4] = lwr.getLabTestAdmFeedbck();
                        row[5] = lwr.getReqdate();

                        model.addRow(row);
                    }
                    
                }
            }
            //userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLabRequest = new javax.swing.JTable();
        jkLabel6 = new javax.swing.JLabel();
        jkLabel1 = new javax.swing.JLabel();
        jlblPatientName = new javax.swing.JLabel();
        jkLabel2 = new javax.swing.JLabel();
        jlblDocName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSpeciType = new javax.swing.JTextField();
        jkLabel5 = new javax.swing.JLabel();
        jtxtLabTestName = new javax.swing.JTextField();
        jkLabel4 = new javax.swing.JLabel();
        jtxtMessage = new javax.swing.JTextField();
        reqTestJButton = new javax.swing.JButton();
        jbackJButton = new javax.swing.JButton();
        jkLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblLabRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Patient", "Specimen Type", "Lab Test  Name", "Lab Test Feedback", "Request Date"
            }
        ));
        jScrollPane1.setViewportView(jtblLabRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 88, 663, 129));

        jkLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkLabel6.setText("LAB TEST REQUEST PAGE");
        add(jkLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 28));

        jkLabel1.setText("Patient Name:");
        add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 247, -1, -1));

        jlblPatientName.setText("<Name>");
        add(jlblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 247, 135, -1));

        jkLabel2.setText("Doctor Name: ");
        add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 247, -1, -1));

        jlblDocName.setText("<Name>");
        add(jlblDocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 247, 135, -1));

        jLabel3.setText("Specimen Type :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 296, -1, -1));
        add(txtSpeciType, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 291, 189, -1));

        jkLabel5.setText("Lab Test Name :");
        add(jkLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 352, -1, -1));
        add(jtxtLabTestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 347, 189, -1));

        jkLabel4.setText("Message :");
        add(jkLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 408, -1, -1));
        add(jtxtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 403, 189, -1));

        reqTestJButton.setText("Request Test");
        reqTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqTestJButtonActionPerformed(evt);
            }
        });
        add(reqTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 459, 175, -1));

        jbackJButton.setText("<<Back");
        jbackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackJButtonActionPerformed(evt);
            }
        });
        add(jbackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 459, -1, -1));

        jkLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/labadmin.jpg"))); // NOI18N
        jkLabel7.setText("jLabel7");
        add(jkLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void reqTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqTestJButtonActionPerformed

        String message = jtxtMessage.getText();
        String labTestName = jtxtLabTestName.getText();
        String labSpecimen = txtSpeciType.getText();
        // String message = messageJTextField.getText();
//        if (message.equals("") || message.isEmpty() || !message.matches("[a-zA-Z]+")) {
//            JOptionPane.showMessageDialog(null, "Please enter something to send.");
//            return;
//        }

        LabWorkRequestService request = new LabWorkRequestService();
        request.setMes(message);
        request.setSendr(userAccount);
        request.setLabTesttName(labTestName);
        request.setSpeciType(labSpecimen);
        request.setStat("Requested");
        request.setPati(patient);
        request.setDoc(doctor);
        request.setReqdate(new Date());
        System.out.println(patient.getPatName());
        //   patient.getPdr().addRequest(request);

        OrganizationService org = null;
       for(Venture enterprise : network.getVentureDirectory().getVentureList())  
       {
            for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof LabOrganizationService) {
                    org = organization;
                    break;
                }
            }
       }
        if (org != null) {
            org.getWorkkQueue().getWorkRequestList().add(request);
            //userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Request message sent");
        populateTable();
        //        String[] to = {"nauka.salot2910@gmail.com", "naukasalot@yahoo.com"};
        //
        //        try {
            //            if (Mail.sendMail("neucare12@gmail.com", "northeastern", "New Test Requested", to)) {
                //                System.out.println("sent");
                //            } else {
                //                System.out.println("serror");
                //            }
            //
            //// TODO add your handling code here:
            //            // TODO add your handling code here:
            //        } catch (MessagingException ex) {
            //            Logger.getLogger(DoctorWorkAreaJPanel2.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        //        JOptionPane.showMessageDialog(this, "Email Sent!");
    }//GEN-LAST:event_reqTestJButtonActionPerformed

    private void jbackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackJButtonActionPerformed

        //        userProcessContainer.remove(this);
        //        Component[] componentArray = userProcessContainer.getComponents();
        //        Component component = componentArray[componentArray.length - 1];
        //        DoctorWorkAreaJPanel2 dwajp= (DoctorWorkAreaJPanel2) component;
        //        dwajp.populateTable();
        //        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        //        layout.previous(userProcessContainer);
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;

        //DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel2) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jbackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbackJButton;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JLabel jkLabel5;
    private javax.swing.JLabel jkLabel6;
    private javax.swing.JLabel jkLabel7;
    private javax.swing.JLabel jlblDocName;
    private javax.swing.JLabel jlblPatientName;
    private javax.swing.JTable jtblLabRequest;
    private javax.swing.JTextField jtxtLabTestName;
    private javax.swing.JTextField jtxtMessage;
    private javax.swing.JButton reqTestJButton;
    private javax.swing.JTextField txtSpeciType;
    // End of variables declaration//GEN-END:variables
}
