/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EquipmentUnitAdminArea;

import Project.EcoSystem;
import Project.Venture.Venture;
import Project.Organization.OrganizationService;
import Project.Organization.OrganizationService.Type;
import Project.Organization.OrganizationDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raveena
 */
public class EquipmentUnitManageOrganizationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EquipmentUnitManageOrganizationsJPanel
     */
    JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
    private OrganizationDirectory organizationDirectory;
    
    public EquipmentUnitManageOrganizationsJPanel(JPanel userProcessContainer, Venture enterprise, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
        populateCombo();
        populateTable();
    }
    private void populateCombo() {
        orgJComboBox.removeAllItems();
        orgJComboBox.addItem(OrganizationService.Type.EquipmentDepartmentService);
        }
      private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jtblOrgEme.getModel();

        model.setRowCount(0);

        for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Object[] row = new Object[3];
            row[0] = organization.getOrgID();
            row[1] = organization.getOrgName();
            row[2] = organization.getTypee().getVal();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblOrgEme = new javax.swing.JTable();
        jkLabel1 = new javax.swing.JLabel();
        orgJComboBox = new javax.swing.JComboBox();
        jkLabel2 = new javax.swing.JLabel();
        jtxtOrgName = new javax.swing.JTextField();
        jbtnAddOrg = new javax.swing.JButton();

        jkLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jkLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jkLabel3.setText("MANAGE EQUIPMENT UNIT ORGANIZATION");

        jtblOrgEme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Type"
            }
        ));
        jScrollPane2.setViewportView(jtblOrgEme);

        jkLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel1.setText("Organization Type :");

        orgJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgJComboBoxActionPerformed(evt);
            }
        });

        jkLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel2.setText("Organization Name :");

        jtxtOrgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOrgNameActionPerformed(evt);
            }
        });

        jbtnAddOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtnAddOrg.setText("Add Organization");
        jbtnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddOrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jkLabel2)
                    .addComponent(jkLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orgJComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 224, Short.MAX_VALUE)
                    .addComponent(jtxtOrgName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jbtnAddOrg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jkLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnAddOrg, jtxtOrgName, orgJComboBox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jkLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jbtnAddOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnAddOrg, jtxtOrgName, orgJComboBox});

    }// </editor-fold>//GEN-END:initComponents

    private void jtxtOrgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOrgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOrgNameActionPerformed

    private void jbtnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddOrgActionPerformed
        // TODO add your handling code here:
        Type type = (Type) orgJComboBox.getSelectedItem();

        if("".equals(jtxtOrgName.getText())) {
            JOptionPane.showMessageDialog(null, "Enter organization name!");
        }
        else {
            
            for(OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        if(organization.getTypee() ==  type)
                        {
                            JOptionPane.showMessageDialog(null, "Organization already Created");
                              jtxtOrgName.setText("");
                            return;
                        }
                    }
            
            OrganizationService organization =  organizationDirectory.createOrganization(type,jtxtOrgName.getText());
            JOptionPane.showMessageDialog(null, "Organization Successfully Created");
            jtxtOrgName.setText("");
            populateTable();
            resetFields();
        }
    }//GEN-LAST:event_jbtnAddOrgActionPerformed

    public void resetFields() {
        jtxtOrgName.setText("");
        
    }
    private void orgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAddOrg;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JTable jtblOrgEme;
    private javax.swing.JTextField jtxtOrgName;
    private javax.swing.JComboBox orgJComboBox;
    // End of variables declaration//GEN-END:variables
}
