/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagementUnitAdminArea;

import Project.EcoSystem;
import Project.Employee.Employee;
import Project.Venture.Venture;
import Project.Organization.AmbulanceOrganizationService;
import Project.Organization.DoctorOrganizationService;
import Project.Organization.OrganizationService;
import Project.Organization.PatientOrganizationService;
import Project.Role.RoleService;
import Project.UserAccount.UserAccountService;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.Patient.PatientLocationMap;

/**
 *
 * @author Raveena
 */
public class ManagementUnitManageUsersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagementUnitManageUsersJPanel
     */
    
     private JPanel userContainer;
    private Venture enterprise;
    private EcoSystem ecosystem;
    
    public ManagementUnitManageUsersJPanel(JPanel userContainer,Venture enterprise,EcoSystem ecosystem) {
        initComponents();
        initComponents();
        this.enterprise = enterprise;
        this.userContainer = userContainer;
        this.ecosystem = ecosystem;
        populateOrgComboBox();
       // employeeJComboBox.removeAllItems();
        populateData();
        lblAmbulance.setVisible(false);
          jtxtAmbNum.setVisible(false);
          jtxtLocation.setVisible(false);
          jbtnLocation.setVisible(false);
          jkLabel7.setVisible(false);
    }
    public void populateOrgComboBox(){
       jorgJComboBox.removeAllItems();
        for(OrganizationService organization :enterprise.getOrganizationDirectory().getOrganizationList() ){
            if(       organization instanceof PatientOrganizationService || organization instanceof DoctorOrganizationService)
            {
                continue;
            }
            else
            {
                  jorgJComboBox.addItem(organization);
            }
        }
        
    }
    
    public void populateEmployeeComboBox(OrganizationService organization){
         employeeJkCombo.removeAllItems();
        
        for (Employee employee : organization.getEmployeeeDirectory().getEmployeeList()){
            employeeJkCombo.addItem(employee);
        }
    }
    
    public void populateRoleComboBox(OrganizationService organization){
        roleJkComboBox.removeAllItems();
          for (RoleService role : organization.getSupportedRole()){
            roleJkComboBox.addItem(role);
        }
    }
    public void ppopulateLongituteLatitude(String locationPoint)
       {
           jtxtLocation.setText(locationPoint);
       }
    
    public void populateData(){
        
        DefaultTableModel model = (DefaultTableModel) juserJTable.getModel();

        model.setRowCount(0);

        for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccountService ua : organization.getUserAccounttDirectory().getUserAccounttList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRolee();
                ((DefaultTableModel) juserJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        juserJTable = new javax.swing.JTable();
        jkLabel2 = new javax.swing.JLabel();
        jorgJComboBox = new javax.swing.JComboBox();
        jkLabel5 = new javax.swing.JLabel();
        employeeJkCombo = new javax.swing.JComboBox();
        roleJkComboBox = new javax.swing.JComboBox();
        jkLabel3 = new javax.swing.JLabel();
        jkLabel6 = new javax.swing.JLabel();
        jkLabel7 = new javax.swing.JLabel();
        jbtnLocation = new javax.swing.JButton();
        jtxtUserName = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JTextField();
        jtxtAmbNum = new javax.swing.JTextField();
        jtxtLocation = new javax.swing.JTextField();
        jcreateUserJButton = new javax.swing.JButton();
        lblAmbulance = new javax.swing.JLabel();
        jkLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jkLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel1.setText("MANAGE USER");

        juserJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        juserJTable.setForeground(new java.awt.Color(25, 56, 82));
        juserJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        juserJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(juserJTable);

        jkLabel2.setText("Organization");

        jorgJComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jorgJComboBox.setForeground(new java.awt.Color(25, 56, 82));
        jorgJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jorgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorgJComboBoxActionPerformed(evt);
            }
        });

        jkLabel5.setText("Employee");

        employeeJkCombo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        employeeJkCombo.setForeground(new java.awt.Color(25, 56, 82));
        employeeJkCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeJkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeJkComboActionPerformed(evt);
            }
        });

        roleJkComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        roleJkComboBox.setForeground(new java.awt.Color(25, 56, 82));
        roleJkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roleJkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleJkComboBoxActionPerformed(evt);
            }
        });

        jkLabel3.setText("Role");

        jkLabel6.setText("UserName");

        jkLabel7.setText("Location");

        jbtnLocation.setText("Set Location");
        jbtnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLocationActionPerformed(evt);
            }
        });

        jtxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserNameActionPerformed(evt);
            }
        });

        jtxtLocation.setEditable(false);
        jtxtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLocationActionPerformed(evt);
            }
        });

        jcreateUserJButton.setBackground(new java.awt.Color(255, 255, 255));
        jcreateUserJButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jcreateUserJButton.setForeground(new java.awt.Color(25, 56, 82));
        jcreateUserJButton.setText("Create");
        jcreateUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcreateUserJButtonActionPerformed(evt);
            }
        });

        lblAmbulance.setText("Ambulance Number");

        jkLabel4.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jkLabel2)
                .addGap(58, 58, 58)
                .addComponent(jorgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jkLabel5)
                .addGap(51, 51, 51)
                .addComponent(employeeJkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jkLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(roleJkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jkLabel6)
                .addGap(51, 51, 51)
                .addComponent(jtxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jkLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblAmbulance)
                .addGap(58, 58, 58)
                .addComponent(jtxtAmbNum, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jkLabel7)
                .addGap(52, 52, 52)
                .addComponent(jtxtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jbtnLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jcreateUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorgJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeJkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleJkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jkLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jkLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAmbulance))
                    .addComponent(jtxtAmbNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtxtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jbtnLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jcreateUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcreateUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcreateUserJButtonActionPerformed
        String userName = jtxtUserName.getText();
        String password = jtxtPassword.getText();
        if(!userName.isEmpty() && !password.isEmpty()){
            OrganizationService organization = (OrganizationService) jorgJComboBox.getSelectedItem();
            if(ecosystem.checkIfUserIsUnique(userName)){
                Employee employee = (Employee) employeeJkCombo.getSelectedItem();
                RoleService role = (RoleService) roleJkComboBox.getSelectedItem();
                

               // for(OrganizationService ambulanceOrg : enterprise.getOrganizationDirectory().getOrganizationList())
               // {
                    if(organization instanceof AmbulanceOrganizationService)
                    {
                        if(jtxtAmbNum.getText().isEmpty() || jtxtLocation.getText().isEmpty() )
                        {
                            JOptionPane.showMessageDialog(null, "PLease enter Ambulance Details !");
                            return;
                        }
                        String ambulanceNumber = jtxtAmbNum.getText();
                        String location = jtxtLocation.getText();
                        organization.getUserAccounttDirectory().createUserAccount(userName, password, employee, role);
                        ecosystem.getAmbulanceDirectory().addNewAmbulancee(employee.getName(),ambulanceNumber, location);
                        System.out.println("ambulanceNumber added -" +ambulanceNumber);
                    }
                    else
                    {
                         organization.getUserAccounttDirectory().createUserAccount(userName, password, employee, role);
                           System.out.println("rec added -" );
                    }

              //  }

                populateData();
                JOptionPane.showMessageDialog(null, "User account Created!");
                jtxtUserName.setText("");
                jtxtPassword.setText("");
               jtxtAmbNum.setText("");
               jtxtLocation.setText("");
            } else{
                JOptionPane.showMessageDialog(null, "Username already exists!");
            }

        } else{
            JOptionPane.showMessageDialog(null, "Enter all fields!");
        }
    }//GEN-LAST:event_jcreateUserJButtonActionPerformed

    private void jbtnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLocationActionPerformed
        // TODO add your handling code here:
        AmbulanceLocationMap createPatient = new AmbulanceLocationMap(userContainer);
        userContainer.add("CreatePatientJPanel",createPatient);
        CardLayout layout=(CardLayout)userContainer.getLayout();
        layout.next(userContainer);
    }//GEN-LAST:event_jbtnLocationActionPerformed

    private void jtxtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLocationActionPerformed

    private void jtxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserNameActionPerformed

    private void roleJkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleJkComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleJkComboBoxActionPerformed

    private void employeeJkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeJkComboActionPerformed
        // TODO add your handling code here:
        jtxtUserName.setText("");
                jtxtPassword.setText("");
               jtxtAmbNum.setText("");
               jtxtLocation.setText("");
    }//GEN-LAST:event_employeeJkComboActionPerformed

    private void jorgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorgJComboBoxActionPerformed
        OrganizationService organization = (OrganizationService) jorgJComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
            for(OrganizationService ambulanceOrg : enterprise.getOrganizationDirectory().getOrganizationList())
            {
                if(organization instanceof AmbulanceOrganizationService)
                {
                    System.out.println("ambulanceORg");
                    lblAmbulance.setVisible(true);
                    jtxtAmbNum.setVisible(true);
                    jtxtLocation.setVisible(true);
                    jbtnLocation.setVisible(true);
                    jkLabel7.setVisible(true);
                    break;
                }
                else
                {
                    System.out.println("ambulanceORg else");
                    lblAmbulance.setVisible(false);
                    jtxtAmbNum.setVisible(false);
                    jtxtLocation.setVisible(false);
                    jbtnLocation.setVisible(false);
                    jkLabel7.setVisible(false);
                    jtxtUserName.setText("");
                jtxtPassword.setText("");
               jtxtAmbNum.setText("");
               jtxtLocation.setText("");

                }
            }

        }
    }//GEN-LAST:event_jorgJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox employeeJkCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnLocation;
    private javax.swing.JButton jcreateUserJButton;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JLabel jkLabel5;
    private javax.swing.JLabel jkLabel6;
    private javax.swing.JLabel jkLabel7;
    private javax.swing.JComboBox jorgJComboBox;
    private javax.swing.JTextField jtxtAmbNum;
    private javax.swing.JTextField jtxtLocation;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtUserName;
    private javax.swing.JTable juserJTable;
    private javax.swing.JLabel lblAmbulance;
    private javax.swing.JComboBox roleJkComboBox;
    // End of variables declaration//GEN-END:variables
}
