/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagementUnitAdminArea;

import Project.EcoSystem;
import Project.Venture.Venture;
import Project.Organization.OrganizationService;
import Project.Organization.OrganizationService.Type;
import Project.Organization.OrganizationDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raveena
 */
public class ManagementUnitOrganizationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagementUnitOrganizationsJPanel
     */
    JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
    private OrganizationDirectory organizationDirectory;
    public ManagementUnitOrganizationsJPanel(JPanel userProcessContainer, Venture enterprise, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
        populateCombo();
        populateTable();
    }
    
     private void populateCombo() {
        orgJComboBox.removeAllItems();
        //organizationJComboBox.addItem(OrganizationService.Type.PersonDepartmentService);
        orgJComboBox.addItem(Type.AmbulanceDepartmentService);
       // organizationJComboBox.addItem(Type.LabDepartmentService);
        orgJComboBox.addItem(Type.PatientDepartmentService);
        orgJComboBox.addItem(Type.ReceptionistDepartmentService);
        orgJComboBox.addItem(Type.DoctorDepartmentService);
        
        }
      private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jtblOrgEme.getModel();

        model.setRowCount(0);
            System.out.println(enterprise.getOrgName());
        for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Object[] row = new Object[3];
            row[0] = organization.getOrgID();
            row[1] = organization.getOrgName();
            row[2] = organization.getTypee().getVal();

            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblOrgEme = new javax.swing.JTable();
        jkLabel1 = new javax.swing.JLabel();
        orgJComboBox = new javax.swing.JComboBox();
        jtxtOrgName = new javax.swing.JTextField();
        jkLabel2 = new javax.swing.JLabel();
        jbtnAddOrg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jkLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jkLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel3.setText("ORGANIZATION MANAGEMENT UNIT ");
        add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 28, -1, -1));

        jtblOrgEme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Type"
            }
        ));
        jScrollPane2.setViewportView(jtblOrgEme);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 90, 437, 108));

        jkLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel1.setText("Organization Type");
        add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 234, -1, -1));

        orgJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(orgJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 228, 171, 29));
        add(jtxtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 287, 171, 29));

        jkLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel2.setText("Organization Name");
        add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 294, -1, -1));

        jbtnAddOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtnAddOrg.setText("Add Organization");
        jbtnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddOrgActionPerformed(evt);
            }
        });
        add(jbtnAddOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 346, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mng.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddOrgActionPerformed
        // TODO add your handling code here:
        Type type = (Type) orgJComboBox.getSelectedItem();

        if("".equals(jtxtOrgName.getText())) 
        {
            JOptionPane.showMessageDialog(null, "Enter organization name!");
        }
        else 
        {
            for(OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        if(organization.getTypee() ==  type)
                        {
                            JOptionPane.showMessageDialog(null, "Organization already Created");
                              jtxtOrgName.setText("");
                            return;
                        }
                    }
            
            OrganizationService organization =  organizationDirectory.createOrganization(type,jtxtOrgName.getText());
            JOptionPane.showMessageDialog(null, "Organization Successfully Created");
            jtxtOrgName.setText("");
            populateTable();
            resetFields();
        }
    }//GEN-LAST:event_jbtnAddOrgActionPerformed

      public void resetFields() {
        jtxtOrgName.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAddOrg;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JTable jtblOrgEme;
    private javax.swing.JTextField jtxtOrgName;
    private javax.swing.JComboBox orgJComboBox;
    // End of variables declaration//GEN-END:variables
}
