/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EquipmentWorkArea;

import Project.EcoSystem;
import Project.Employee.Employee;
import Project.Venture.Venture;
import Project.Equipment.EquipmentService;
import Project.Equipment.EquipmentList;
import Project.Network.NetworkService;
import Project.Organization.OrganizationService;
import Project.UserAccount.UserAccountService;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.EmergencyUnitAdminArea.EmergencyUnitManageEmployeeJPanel;

/**
 *
 * @author Raveena
 */
public class EquipmentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EquipmentWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
    EquipmentList equipmentList;
    NetworkService network;
    UserAccountService userAccount;
    OrganizationService organization;
    public EquipmentWorkAreaJPanel(JPanel userProcessContainer, UserAccountService userAccount,NetworkService network, Venture enterprise,
            OrganizationService organization,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.equipmentList = ecosystem.getEquipmentList();
        this.network = network;
        this.userAccount = userAccount;
        this.organization = organization;
        populateTable();
    }
    
    public void populateTable()
    {
         DefaultTableModel model = (DefaultTableModel) jtblEquipList.getModel();

        model.setRowCount(0);

        for (EquipmentService equipment : ecosystem.getEquipmentList().getEquipmentList()) {
            Object[] row = new Object[5];
            double cost = equipment.getPrice();
            int qunt = Integer.parseInt(equipment.getAvailableeQuant());
            row[0] = equipment.getEquiID();
            row[1] = equipment.getEquiName();
            row[2] = equipment.getAvailableeQuant();
            row[3] = equipment.getPrice();
            row[4] = cost * qunt ;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jkLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEquipList = new javax.swing.JTable();
        jkButton1 = new javax.swing.JButton();
        jkButton2 = new javax.swing.JButton();
        jkLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jkLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel1.setText("EQUIPMENT ADMIN PAGE");
        add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 19, -1, 40));

        jtblEquipList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Equipment ID", "Equipment Name", "Available Quantity", "Equipment Cost", "Total Cost"
            }
        ));
        jScrollPane1.setViewportView(jtblEquipList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 89, 668, 183));

        jkButton1.setText("Add New Equipment");
        jkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkButton1ActionPerformed(evt);
            }
        });
        add(jkButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 322, 220, -1));

        jkButton2.setText("Request for Equipment");
        jkButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkButton2ActionPerformed(evt);
            }
        });
        add(jkButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 322, 220, -1));

        jkLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/equipmentworkarea.png"))); // NOI18N
        add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void jkButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkButton1ActionPerformed
        // TODO add your handling code here:
         AddEquipmentJPanel mujp = new AddEquipmentJPanel(userProcessContainer, enterprise, ecosystem);
        userProcessContainer.add("AddEquipmentJPanel",mujp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jkButton1ActionPerformed

    private void jkButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkButton2ActionPerformed
        // TODO add your handling code here:
         EquipmentRequestJPanel mujp = new EquipmentRequestJPanel(userProcessContainer,network, enterprise,organization , userAccount,ecosystem);
        userProcessContainer.add("AddEquipmentJPanel",mujp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jkButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jkButton1;
    private javax.swing.JButton jkButton2;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JTable jtblEquipList;
    // End of variables declaration//GEN-END:variables
}
