/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EquipmentWorkArea;

import Project.EcoSystem;
import Project.Venture.Venture;
import Project.Equipment.EquipmentService;
import Project.Network.NetworkService;
import Project.Organization.BillingOrganizationService;
import Project.Organization.EmergencyOrganizationService;
import Project.Organization.EquipmentOrganizationService;
import Project.Organization.OrganizationService;
import Project.Organization.PatientOrganizationService;
import Project.UserAccount.UserAccountService;
import Project.WorkQueue.BillingWorkRequestService;
import Project.WorkQueue.EmergencyPatientRequestService;
import Project.WorkQueue.WorkRequestService;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raveena
 */
public class EquipmentRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EquipmentRequestJPanel
     */
     JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
    NetworkService network;
    UserAccountService userAccount;
    OrganizationService organization;
    public EquipmentRequestJPanel(JPanel userProcessContainer, NetworkService network,Venture enterprise,OrganizationService organization
            ,UserAccountService userAccount, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount =userAccount;
        this.organization = organization;
        System.out.println("Beofre conmbo");
        populateCombo();
        populateRequestTable();
    }

    public void populateRequestTable()
    {
        DefaultTableModel model = (DefaultTableModel) jtblEquipReq.getModel();

        model.setRowCount(0);
         OrganizationService Billingorg = null;
       for(NetworkService network : ecosystem.getNetworkList())
       {
            for(Venture enterprise : network.getVentureDirectory().getVentureList())  
            {
              for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                  if(organization instanceof BillingOrganizationService)
                  {
                         Billingorg = organization;
                         break;
                     }
                 }
            }
       }
       
       for(WorkRequestService wr : Billingorg.getWorkkQueue().getWorkRequestList())
       {
           if(wr instanceof BillingWorkRequestService )
           {
               BillingWorkRequestService billWrkReq = (BillingWorkRequestService)wr;
                Object[] row = new Object[10];
                
                row[0] = billWrkReq;
                row[1] = billWrkReq.getSendr().getEmployeee().getName();
                row[2] = billWrkReq.getEquiId();
                row[3] = billWrkReq.getEquiName();
                row[4] = billWrkReq.getEqui().getAvailableeQuant() ;
                row[5] = billWrkReq.getEqui().getPrice();
                row[6] = billWrkReq.getEquiPrice();
                row[7] = billWrkReq.getStat();
                row[8] = billWrkReq.getReqDate();
                row[9] = billWrkReq.getResolvDate();
                model.addRow(row);
           }
           
       }
           //BillingWorkRequest
    }
    
     private void populateCombo() {
        equipJCombBox.removeAllItems();
        
        for(EquipmentService equipment : ecosystem.getEquipmentList().getEquipmentList())
        {
            equipJCombBox.addItem(equipment);
        }
     }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkLabel1 = new javax.swing.JLabel();
        jkLabel3 = new javax.swing.JLabel();
        jtxtEquipCost = new javax.swing.JTextField();
        jkLabel4 = new javax.swing.JLabel();
        txtquan = new javax.swing.JTextField();
        jkLabel5 = new javax.swing.JLabel();
        txtTotCost = new javax.swing.JTextField();
        btnBilliReq = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblEquipReq = new javax.swing.JTable();
        jkLabel6 = new javax.swing.JLabel();
        equipJCombBox = new javax.swing.JComboBox();
        jbtnBack = new javax.swing.JButton();

        jkLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel1.setText("EQUIPMENT REQUEST PAGE");

        jkLabel3.setText("Equipment Price :");

        jkLabel4.setText("Equipment Qunatity :");

        txtquan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtquanFocusLost(evt);
            }
        });
        txtquan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquanActionPerformed(evt);
            }
        });

        jkLabel5.setText("Total Cost :");

        txtTotCost.setEditable(false);

        btnBilliReq.setText("Request for Fund");
        btnBilliReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilliReqActionPerformed(evt);
            }
        });

        jtblEquipReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "BillingRequestId", "Sender", "EquipmentId", "EquipmentName", "No of Units", "Equipment Price", "totalEquipmentCost", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane2.setViewportView(jtblEquipReq);

        jkLabel6.setText("Select Equipment :");

        equipJCombBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        equipJCombBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipJCombBoxActionPerformed(evt);
            }
        });

        jbtnBack.setText("<< Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jkLabel4)
                            .addComponent(jkLabel5)
                            .addComponent(jkLabel6)
                            .addComponent(jkLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtquan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtEquipCost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equipJCombBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 179, Short.MAX_VALUE)
                            .addComponent(txtTotCost)
                            .addComponent(btnBilliReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBilliReq, equipJCombBox, jtxtEquipCost, txtTotCost, txtquan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkLabel6)
                    .addComponent(equipJCombBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkLabel3)
                    .addComponent(jtxtEquipCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkLabel4)
                    .addComponent(txtquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkLabel5)
                    .addComponent(txtTotCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBilliReq)
                    .addComponent(jbtnBack))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBilliReq, equipJCombBox, jtxtEquipCost, txtTotCost, txtquan});

    }// </editor-fold>//GEN-END:initComponents

    private void equipJCombBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipJCombBoxActionPerformed
        // TODO add your handling code here:
        EquipmentService equipment = (EquipmentService) equipJCombBox.getSelectedItem();
        if (equipment != null){
          jtxtEquipCost.setText(String.valueOf(equipment.getPrice()));
          
          //Double totalcost = Integer.parseInt(txtquant.getText()) * Double.parseDouble(txtEquipCost.getText());
         // txtTotalCost.setText(String.valueOf(totalcost));
          
        }
    }//GEN-LAST:event_equipJCombBoxActionPerformed

    private void btnBilliReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilliReqActionPerformed
        // TODO add your handling code here:
        EquipmentService equipment = (EquipmentService) equipJCombBox.getSelectedItem();
         OrganizationService Billingorg = null;
       for(Venture enterprise : network.getVentureDirectory().getVentureList())  
       {
         for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             if(organization instanceof BillingOrganizationService)
             {
                    Billingorg = organization;
                    break;
                }
            }
       }
         
        
        BillingWorkRequestService billingReq = new BillingWorkRequestService();
        billingReq.setEquiId(equipment.getEquiID());
        billingReq.setEquiName(equipment.getEquiName());
        billingReq.setEqui(equipment);
        billingReq.setSendr(userAccount);
        billingReq.setSenderNet(network);
        billingReq.setSenderOrg(organization);
        billingReq.setRecieverNet(network);
        billingReq.setRecieverOrg(Billingorg);
        billingReq.setEquiPrice(Double.parseDouble(txtTotCost.getText()));
        billingReq.setNumberOfUnits(Integer.parseInt(txtquan.getText()));
        billingReq.setReqDate(new Date());
        billingReq.setStat("Fund Requested");
        
       
          
        
        //billingReq.setRecieverOrganization(Emeorg);
         for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             if(organization instanceof EquipmentOrganizationService                        )
             {
                   billingReq.setSenderOrg(organization); 
                    break;
                }
            }
        
        Billingorg.getWorkkQueue().addWorkRequest(billingReq);
        //System.out.println(billingReq.getEmergencyRequestId());
        populateRequestTable();
        
        
        
    }//GEN-LAST:event_btnBilliReqActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
             userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EquipmentWorkAreaJPanel sysAdminwjp = (EquipmentWorkAreaJPanel) component;
        sysAdminwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void txtquanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquanActionPerformed

    private void txtquanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtquanFocusLost
        // TODO add your handling code here:
        String qunat = txtquan.getText();
        if(!qunat.isEmpty())
        {
         Double totalcost = Integer.parseInt(txtquan.getText()) * Double.parseDouble(jtxtEquipCost.getText());
         txtTotCost.setText(String.valueOf(totalcost));
        }
    }//GEN-LAST:event_txtquanFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilliReq;
    private javax.swing.JComboBox equipJCombBox;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JLabel jkLabel5;
    private javax.swing.JLabel jkLabel6;
    private javax.swing.JTable jtblEquipReq;
    private javax.swing.JTextField jtxtEquipCost;
    private javax.swing.JTextField txtTotCost;
    private javax.swing.JTextField txtquan;
    // End of variables declaration//GEN-END:variables
}
