/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmergencyUnitAdminArea;

import Project.EcoSystem;
import Project.Employee.Employee;
import Project.Venture.Venture;
import Project.Organization.OrganizationService;
import Project.Organization.OrganizationDirectory;
import Project.Organization.PatientOrganizationService;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Dell
 */
public class EmergencyUnitManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmergencyUnitManageEmployeeJPanel
     */
     JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
    private OrganizationDirectory organizationDirectory;
    public EmergencyUnitManageEmployeeJPanel(JPanel userProcessContainer, Venture enterprise, EcoSystem ecosystem) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
         
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkLabel1 = new javax.swing.JLabel();
        jorganizationJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jorganizationJTable = new javax.swing.JTable();
        jkLabel3 = new javax.swing.JLabel();
        jorganizationEmpJComboBox = new javax.swing.JComboBox();
        jkLabel2 = new javax.swing.JLabel();
        jnameJTextField = new javax.swing.JTextField();
        jaddJButton = new javax.swing.JButton();
        jkLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jkLabel1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jkLabel1.setText("Organization");
        add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 87, -1, -1));

        jorganizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jorganizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorganizationJComboBoxActionPerformed(evt);
            }
        });
        add(jorganizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 84, 200, -1));

        jorganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jorganizationJTable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jorganizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 141, 480, 107));

        jkLabel3.setText("Organization");
        add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 283, -1, -1));

        jorganizationEmpJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jorganizationEmpJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorganizationEmpJComboBoxActionPerformed(evt);
            }
        });
        add(jorganizationEmpJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 278, 200, 29));

        jkLabel2.setText("Name");
        add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 343, -1, -1));

        jnameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameJTextFieldActionPerformed(evt);
            }
        });
        add(jnameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 337, 200, 29));

        jaddJButton.setText("Create Employee");
        jaddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddJButtonActionPerformed(evt);
            }
        });
        add(jaddJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 396, 200, -1));

        jkLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel4.setText("EMERGENCY MANAGE EMPLOYEE");
        add(jkLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 23, -1, 31));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/emergencyadmin.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 810, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jorganizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorganizationJComboBoxActionPerformed
        OrganizationService organization = (OrganizationService) jorganizationJComboBox.getSelectedItem();
        if (organization != null) {
            populateTable(organization);
        }
    }//GEN-LAST:event_jorganizationJComboBoxActionPerformed

     public void populateOrganizationComboBox() {
        jorganizationJComboBox.removeAllItems();

        for (OrganizationService organization : organizationDirectory.getOrganizationList()) {
//            if (organization instanceof PatientOrganizationService) {
//                continue;
//            } else {
                jorganizationJComboBox.addItem(organization);
          //  }
        }
    }

    public void populateOrganizationEmpComboBox() {
        jorganizationEmpJComboBox.removeAllItems();
//        for (OrganizationService organization : organizationDir.getOrganizationList()){
//           if(organization instanceof PatientOrganizationService)
//           {
//               continue;
//           }
//           else{
//            organizationJComboBox.addItem(organization);}
//        }

        for (OrganizationService organization : organizationDirectory.getOrganizationList()) {
            jorganizationEmpJComboBox.addItem(organization);
        }
    }
     private void populateTable(OrganizationService organization) {
       //To change body of generated methods, choose Tools | Templates.
       
       DefaultTableModel model = (DefaultTableModel) jorganizationJTable.getModel();

        model.setRowCount(0);

        for (Employee employee : organization.getEmployeeeDirectory().getEmployeeList()) {
            Object[] row = new Object[2];
            row[0] = employee.getId();
            row[1] = employee.getName();
            model.addRow(row);
        }
//      organizationJTable.setBackground(Color.yellow);
//      organizationJTable.setForeground(Color.white);
      JTableHeader tableHeader = jorganizationJTable.getTableHeader();
      tableHeader.setBackground(Color.BLACK);
      tableHeader.setForeground(Color.blue);
      JFrame frame = new JFrame();
       
    }
    private void jorganizationEmpJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorganizationEmpJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jorganizationEmpJComboBoxActionPerformed

    private void jaddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddJButtonActionPerformed

        OrganizationService organization = (OrganizationService) jorganizationEmpJComboBox.getSelectedItem();
        String name = jnameJTextField.getText();

        organization.getEmployeeeDirectory().createEmployee(name);
        jnameJTextField.setText("");
        populateTable(organization);
    }//GEN-LAST:event_jaddJButtonActionPerformed

    private void jnameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jaddJButton;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JTextField jnameJTextField;
    private javax.swing.JComboBox jorganizationEmpJComboBox;
    private javax.swing.JComboBox jorganizationJComboBox;
    private javax.swing.JTable jorganizationJTable;
    // End of variables declaration//GEN-END:variables

   
}
