/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EmergencyUnitAdminArea;

import Project.EcoSystem;
import Project.Venture.Venture;
import Project.Organization.OrganizationService;
import Project.Organization.OrganizationService.Type;
import Project.Organization.OrganizationDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class EmergencyUnitManageOrganizationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmergencyUnitManageOrganizationsJPanel
     */
    JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
     private OrganizationDirectory organizationDirectory;
    public EmergencyUnitManageOrganizationsJPanel(JPanel userProcessContainer, Venture enterprise, EcoSystem ecosystem) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
        populateCombo();
        populateTable();
    }

    private void populateCombo() {
        jorganizationJComboBox.removeAllItems();
        jorganizationJComboBox.addItem(Type.EmergencyDepartmentService);
//        organizationJComboBox.addItem(Type.AmbulanceDepartmentService);
//        organizationJComboBox.addItem(Type.LabDepartmentService);
//        organizationJComboBox.addItem(Type.PatientDepartmentService);
//        organizationJComboBox.addItem(Type.ReceptionistDepartmentService);
//        organizationJComboBox.addItem(Type.DoctorDepartmentService);
        }
     
      private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrgEmerg.getModel();

        model.setRowCount(0);

        for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Object[] row = new Object[3];
            row[0] = organization.getOrgID();
            row[1] = organization.getOrgName();
            row[2] = organization.getTypee().getVal();

            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrgEmerg = new javax.swing.JTable();
        jkLabel1 = new javax.swing.JLabel();
        jkLabel2 = new javax.swing.JLabel();
        jtxtOrgName = new javax.swing.JTextField();
        jbtnAddOrg = new javax.swing.JButton();
        jkLabel3 = new javax.swing.JLabel();
        jorganizationJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrgEmerg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Type"
            }
        ));
        jScrollPane2.setViewportView(tblOrgEmerg);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 81, 564, 155));

        jkLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel1.setText("Organization Type :");
        add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 266, -1, 30));

        jkLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel2.setText("Organization Name :");
        add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 327, -1, 30));

        jtxtOrgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOrgNameActionPerformed(evt);
            }
        });
        add(jtxtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 327, 200, 30));

        jbtnAddOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtnAddOrg.setText("Add Organization");
        jbtnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddOrgActionPerformed(evt);
            }
        });
        add(jbtnAddOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 387, 200, 32));

        jkLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jkLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel3.setText("EMERGENCY MANAGE ORGANIZATION ");
        add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 31));

        jorganizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jorganizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorganizationJComboBoxActionPerformed(evt);
            }
        });
        add(jorganizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 267, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/emergencyadmin.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 880, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddOrgActionPerformed
        // TODO add your handling code here:
      Type type = (Type) jorganizationJComboBox.getSelectedItem();
        
        if("".equals(jtxtOrgName.getText())) {
            JOptionPane.showMessageDialog(null, "Enter organization name!"); 
        }
        else {
            for(OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        if(organization.getTypee() ==  type)
                        {
                            JOptionPane.showMessageDialog(null, "Organization already Created");
                              jtxtOrgName.setText("");
                            return;
                        }
                    }
            
            
            
            OrganizationService organization =  organizationDirectory.createOrganization(type,jtxtOrgName.getText());
            JOptionPane.showMessageDialog(null, "Organization Successfully Created");
            jtxtOrgName.setText("");
            populateTable();
            resetFields();
        }
    }//GEN-LAST:event_jbtnAddOrgActionPerformed

    private void jorganizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorganizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jorganizationJComboBoxActionPerformed

    private void jtxtOrgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOrgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOrgNameActionPerformed

      public void resetFields() {
        jtxtOrgName.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAddOrg;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JComboBox jorganizationJComboBox;
    private javax.swing.JTextField jtxtOrgName;
    private javax.swing.JTable tblOrgEmerg;
    // End of variables declaration//GEN-END:variables
}
