/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccountingUnitAdminArea;

import Project.EcoSystem;
import Project.Employee.Employee;
import Project.Venture.Venture;
import Project.Organization.OrganizationService;
import Project.Organization.OrganizationDirectory;
import Project.Organization.PatientOrganizationService;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak Khamkar
 */
public class AccountingUnitManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountingUnitManageEmployeeJPanel
     */
    JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
    private OrganizationDirectory organizationDirectory;
    
    public AccountingUnitManageEmployeeJPanel(JPanel userProcessContainer, Venture enterprise, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
         
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jkLabel1 = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jorganizationJTable = new javax.swing.JTable();
        jkLabel3 = new javax.swing.JLabel();
        jorganizationEmpJComboBox = new javax.swing.JComboBox();
        jkLabel2 = new javax.swing.JLabel();
        jnameJTextField = new javax.swing.JTextField();
        jaddJButton = new javax.swing.JButton();
        jkLabel4 = new javax.swing.JLabel();
        jkLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jkLabel1.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        jkLabel1.setText("Organization");
        jPanel1.add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 88, -1, -1));

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 85, 250, -1));

        jorganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jorganizationJTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 142, 480, 113));

        jkLabel3.setText("Organization");
        jPanel1.add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 285, -1, -1));

        jorganizationEmpJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jorganizationEmpJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorganizationEmpJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jorganizationEmpJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 285, 250, 29));

        jkLabel2.setText("Name");
        jPanel1.add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 350, -1, -1));
        jPanel1.add(jnameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 344, 250, 29));

        jaddJButton.setText("Create Employee");
        jaddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jaddJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 403, 250, -1));

        jkLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel4.setText("MANAGE ACCOUNTING EMPLOYEE");
        jPanel1.add(jkLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 20, 440, 35));

        jkLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/accounting.png"))); // NOI18N
        jPanel1.add(jkLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -4, 800, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        OrganizationService organization = (OrganizationService) organizationJComboBox.getSelectedItem();
        if (organization != null) {
            populateTable(organization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed
     private void populateTable(OrganizationService organization) {
       //To change body of generated methods, choose Tools | Templates.
       DefaultTableModel model = (DefaultTableModel) jorganizationJTable.getModel();

        model.setRowCount(0);

        for (Employee employee : organization.getEmployeeeDirectory().getEmployeeList()) {
            Object[] row = new Object[2];
            row[0] = employee.getId();
            row[1] = employee.getName();
            model.addRow(row);
        }
       
    }
    public void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (OrganizationService organization : organizationDirectory.getOrganizationList()) {
            if (organization instanceof PatientOrganizationService) {
                continue;
            } else {
                organizationJComboBox.addItem(organization);
            }
        }
    }
    public void populateOrganizationEmpComboBox() {
        jorganizationEmpJComboBox.removeAllItems();
//        for (OrganizationService organization : organizationDir.getOrganizationList()){
//           if(organization instanceof PatientOrganizationService)
//           {
//               continue;
//           }
//           else{
//            organizationJComboBox.addItem(organization);}
//        }

        for (OrganizationService organization : organizationDirectory.getOrganizationList()) {
            jorganizationEmpJComboBox.addItem(organization);
        }
    }
    private void jorganizationEmpJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorganizationEmpJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jorganizationEmpJComboBoxActionPerformed

    private void jaddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddJButtonActionPerformed

        OrganizationService organization = (OrganizationService)jorganizationEmpJComboBox.getSelectedItem();
        String name = jnameJTextField.getText();

        organization.getEmployeeeDirectory().createEmployee(name);
        jnameJTextField.setText("");
        populateTable(organization);
    }//GEN-LAST:event_jaddJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jaddJButton;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JLabel jkLabel5;
    private javax.swing.JTextField jnameJTextField;
    private javax.swing.JComboBox jorganizationEmpJComboBox;
    private javax.swing.JTable jorganizationJTable;
    private javax.swing.JComboBox organizationJComboBox;
    // End of variables declaration//GEN-END:variables
}
