/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccountingUnitAdminArea;

import Project.EcoSystem;
import Project.Venture.Venture;
import Project.Organization.BillingOrganizationService;
import Project.Organization.OrganizationService;
import Project.Organization.OrganizationService.Type;
import Project.Organization.OrganizationDirectory;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import Project.Utils.ValidationService;

/**
 *
 * @author Deepak Khamkar
 */
public class AccountingUnitManageOrganizationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountingUnitManageOrganizationsJPanel
     */
    JPanel userProcessContainer;
    Venture enterprise;
    EcoSystem ecosystem;
    private OrganizationDirectory organizationDirectory;
    
    public AccountingUnitManageOrganizationsJPanel(JPanel userProcessContainer, Venture enterprise, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.organizationDirectory = enterprise.getOrganizationDirectory();
        populateCombo();
        populateTable();
    }
    
     private void populateCombo() {
        jorganizationJComboBox.removeAllItems();
        jorganizationJComboBox.addItem(OrganizationService.Type.BillingDepartmentService);
        }
      private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jtblOrgEme.getModel();

        model.setRowCount(0);

        for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Object[] row = new Object[3];
            row[0] = organization.getOrgID();
            row[1] = organization.getOrgName();
            row[2] = organization.getTypee().getVal();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblOrgEme = new javax.swing.JTable();
        jkLabel1 = new javax.swing.JLabel();
        jkLabel2 = new javax.swing.JLabel();
        jtxtOrgName = new javax.swing.JTextField();
        jbtnAddOrg = new javax.swing.JButton();
        jkLabel3 = new javax.swing.JLabel();
        jorganizationJComboBox = new javax.swing.JComboBox();
        jkLabel4 = new javax.swing.JLabel();
        jtxtfund = new javax.swing.JTextField();
        jkLabel5 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblOrgEme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Type"
            }
        ));
        jScrollPane2.setViewportView(jtblOrgEme);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 564, 120));

        jkLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel1.setText("Organization Type :");
        jPanel1.add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 230, -1, 30));

        jkLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel2.setText("Organization Name :");
        jPanel1.add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, 30));

        jtxtOrgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOrgNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 292, 200, 32));

        jbtnAddOrg.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jbtnAddOrg.setText("Add Organization");
        jbtnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddOrgActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAddOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 416, 200, 32));

        jkLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jkLabel3.setText("Manage Accounting Organization ");
        jPanel1.add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 20, -1, 31));

        jorganizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jorganizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorganizationJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jorganizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 230, 200, 32));

        jkLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jkLabel4.setText("Organization Fund :");
        jPanel1.add(jkLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 357, 127, 26));

        jtxtfund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfundActionPerformed(evt);
            }
        });
        jtxtfund.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtfundKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtfund, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 354, 200, 32));

        jkLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/accounting.png"))); // NOI18N
        jPanel1.add(jkLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtOrgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOrgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtOrgNameActionPerformed

    private void jbtnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddOrgActionPerformed
        // TODO add your handling code here:
        Type type = (Type) jorganizationJComboBox.getSelectedItem();

        if("".equals(jtxtOrgName.getText())) {
            JOptionPane.showMessageDialog(null, "Enter organization name!");
        }
         if("".equals(jtxtfund.getText()))
            {
                 JOptionPane.showMessageDialog(null, "Please enter funds!");
                // return;
            }
        else {
            OrganizationService organization =  organizationDirectory.createOrganization(type,jtxtOrgName.getText());
            BillingOrganizationService bill = (BillingOrganizationService) organization;
            
            if(!jtxtfund.getText().isEmpty())
            {
                bill.setFunds(Double.parseDouble(jtxtfund.getText()));
                System.out.println("Assigned fund to organization" + jtxtfund.getText());
            }
            JOptionPane.showMessageDialog(null, "Organization Successfully Created");
            jtxtOrgName.setText("");
            jtxtfund.setText("");
            populateTable();
            resetFields();
        }
    }//GEN-LAST:event_jbtnAddOrgActionPerformed

     public void resetFields() {
        jtxtOrgName.setText("");        
    }
    private void jorganizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorganizationJComboBoxActionPerformed
        // TODO add your handling code here:
       // validateInteger(evt, txtfund);
       
    }//GEN-LAST:event_jorganizationJComboBoxActionPerformed

    private void jtxtfundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfundActionPerformed

    private void jtxtfundKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfundKeyReleased
        // TODO add your handling code here:
         ValidationService.validateInteger(evt, jtxtfund);
    }//GEN-LAST:event_jtxtfundKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAddOrg;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JLabel jkLabel5;
    private javax.swing.JComboBox jorganizationJComboBox;
    private javax.swing.JTable jtblOrgEme;
    private javax.swing.JTextField jtxtOrgName;
    private javax.swing.JTextField jtxtfund;
    // End of variables declaration//GEN-END:variables
}
