/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccountingUnitAdminArea;

import Project.EcoSystem;
import Project.Employee.Employee;
import Project.Venture.Venture;
import Project.Organization.OrganizationService;
import Project.Role.RoleService;
import Project.UserAccount.UserAccountService;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak Khamkar
 */
public class AccountUnitManageUsersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountUnitManageUsersJPanel
     */
    
     private JPanel userContainer;
    private Venture enterprise;
    private EcoSystem ecosystem;
    
    public AccountUnitManageUsersJPanel(JPanel userContainer,Venture enterprise,EcoSystem ecosystem) {
        initComponents();
        this.enterprise = enterprise;
        this.userContainer = userContainer;
        this.ecosystem = ecosystem;
        populateOrgComboBox();
       // employeeJComboBox.removeAllItems();
        populateData();
    }

    public void populateOrgComboBox(){
       jorgJComboBox.removeAllItems();
        for(OrganizationService organization :enterprise.getOrganizationDirectory().getOrganizationList() ){
            jorgJComboBox.addItem(organization);
        }
        
    }
    
    public void populateEmployeeComboBox(OrganizationService organization){
         jemployeeJCombo.removeAllItems();
        
        for (Employee employee : organization.getEmployeeeDirectory().getEmployeeList()){
            jemployeeJCombo.addItem(employee);
        }
    }
    
    public void populateRoleComboBox(OrganizationService organization){
        jroleJComboBox.removeAllItems();
          for (RoleService role : organization.getSupportedRole()){
            jroleJComboBox.addItem(role);
        }
    }
    
    
    public void populateData(){
        
        DefaultTableModel model = (DefaultTableModel) userJkTable.getModel();

        model.setRowCount(0);

        for (OrganizationService organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccountService ua : organization.getUserAccounttDirectory().getUserAccounttList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRolee();
                ((DefaultTableModel) userJkTable.getModel()).addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJkTable = new javax.swing.JTable();
        jkLabel1 = new javax.swing.JLabel();
        jkLabel2 = new javax.swing.JLabel();
        jkLabel3 = new javax.swing.JLabel();
        jkLabel4 = new javax.swing.JLabel();
        jkLabel5 = new javax.swing.JLabel();
        jkLabel6 = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JTextField();
        jorgJComboBox = new javax.swing.JComboBox();
        jemployeeJCombo = new javax.swing.JComboBox();
        jroleJComboBox = new javax.swing.JComboBox();
        jcreateUserJButton = new javax.swing.JButton();
        jkLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userJkTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        userJkTable.setForeground(new java.awt.Color(25, 56, 82));
        userJkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userJkTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(userJkTable);
        if (userJkTable.getColumnModel().getColumnCount() > 0) {
            userJkTable.getColumnModel().getColumn(0).setHeaderValue("User Name");
            userJkTable.getColumnModel().getColumn(1).setHeaderValue("Role");
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 93, 500, 179));

        jkLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jkLabel1.setText("MANAGE USER");
        jPanel1.add(jkLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 200, 26));

        jkLabel2.setText("Organization:");
        jPanel1.add(jkLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 308, 116, 24));

        jkLabel3.setText("Role:");
        jPanel1.add(jkLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 395, 116, 24));

        jkLabel4.setText("Password:");
        jPanel1.add(jkLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 485, 116, 24));

        jkLabel5.setText("Employee:");
        jPanel1.add(jkLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, 24));

        jkLabel6.setText("UserName:");
        jPanel1.add(jkLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 441, 116, 24));

        jtxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 440, 228, -1));
        jPanel1.add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 484, 228, -1));

        jorgJComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jorgJComboBox.setForeground(new java.awt.Color(25, 56, 82));
        jorgJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jorgJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorgJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jorgJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 305, 228, -1));

        jemployeeJCombo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jemployeeJCombo.setForeground(new java.awt.Color(25, 56, 82));
        jemployeeJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jemployeeJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemployeeJComboActionPerformed(evt);
            }
        });
        jPanel1.add(jemployeeJCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 350, 228, -1));

        jroleJComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jroleJComboBox.setForeground(new java.awt.Color(25, 56, 82));
        jroleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jroleJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jroleJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jroleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 395, 228, -1));

        jcreateUserJButton.setBackground(new java.awt.Color(255, 255, 255));
        jcreateUserJButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jcreateUserJButton.setForeground(new java.awt.Color(25, 56, 82));
        jcreateUserJButton.setText("Create");
        jcreateUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcreateUserJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jcreateUserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 546, 210, -1));

        jkLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/accounting.png"))); // NOI18N
        jPanel1.add(jkLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void jorgJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorgJComboBoxActionPerformed
        OrganizationService organization = (OrganizationService) jorgJComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_jorgJComboBoxActionPerformed

    private void jemployeeJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemployeeJComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemployeeJComboActionPerformed

    private void jroleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jroleJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jroleJComboBoxActionPerformed

    private void jcreateUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcreateUserJButtonActionPerformed
        String userName = jtxtUserName.getText();
        String password = jtxtPassword.getText();
        if(!userName.isEmpty() && !password.isEmpty()){
            OrganizationService organization = (OrganizationService) jorgJComboBox.getSelectedItem();
            if(ecosystem.checkIfUserIsUnique(userName)){
                Employee employee = (Employee) jemployeeJCombo.getSelectedItem();
                RoleService role = (RoleService) jroleJComboBox.getSelectedItem();
                organization.getUserAccounttDirectory().createUserAccount(userName, password, employee, role);
                populateData();
                JOptionPane.showMessageDialog(null, "User account Created!");
                jtxtUserName.setText("");
                jtxtPassword.setText("");
            } else{
                JOptionPane.showMessageDialog(null, "Username already exists!");
            }

        } else{
            JOptionPane.showMessageDialog(null, "Enter all fields!");
        }
    }//GEN-LAST:event_jcreateUserJButtonActionPerformed

    private void jtxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jcreateUserJButton;
    private javax.swing.JComboBox jemployeeJCombo;
    private javax.swing.JLabel jkLabel1;
    private javax.swing.JLabel jkLabel2;
    private javax.swing.JLabel jkLabel3;
    private javax.swing.JLabel jkLabel4;
    private javax.swing.JLabel jkLabel5;
    private javax.swing.JLabel jkLabel6;
    private javax.swing.JLabel jkLabel7;
    private javax.swing.JComboBox jorgJComboBox;
    private javax.swing.JComboBox jroleJComboBox;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtUserName;
    private javax.swing.JTable userJkTable;
    // End of variables declaration//GEN-END:variables
}
